(define (domain hybrid_domain)
  (:requirements :durative-actions :typing :fluents :numeric-fluents)
  (:types robot location object)
  (:predicates
    (at ?r - robot ?l - location)
    (connected ?from ?to - location)
    (holding ?r - robot ?o - object)
    (clear ?o - object)
    (poured ?o - object ?t - object)
    (reachable ?from ?to - location)
    (battery-ok ?r - robot)
    (collision-free ?from ?to - location)
    (motion-validated ?from ?to - location)
    (object-at ?o - object ?l - location)
    (grasp-validated ?o - object ?l - location)
  )
  (:functions
    (distance ?from ?to - location)
    (battery-level ?r - robot)
    (travel-time ?from ?to - location)
    (collision-cost ?from ?to - location)
    (path-clearance ?from ?to - location)
  )
  (:process battery-drain
    :parameters (?r - robot)
    :precondition (moving ?r)
    :effect (decrease (battery-level ?r) (* #t 0.05))
  )
  (:durative-action move
    :parameters (?r - robot ?from ?to - location)
    :duration (= ?duration (travel-time ?from ?to))
    :condition (and (at start (at ?r ?from))
                    (at start (reachable ?from ?to))
                    (at start (collision-free ?from ?to))
                    (over all (battery-ok ?r))
                    (over all (>= (battery-level ?r) (* (distance ?from ?to) 0.1))))
    :effect (and (at start (not (at ?r ?from)))
                 (at end (at ?r ?to))
                 (at end (decrease (battery-level ?r) (* (distance ?from ?to) 0.1))))
  )
  (:durative-action pick
    :parameters (?r - robot ?o - object ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?r ?l))
                    (at start (clear ?o))
                    (at start (object-at ?o ?l))
                    (at start (grasp-validated ?o ?l))
                    (over all (>= (battery-level ?r) 0.05)))
    :effect (and (at end (holding ?r ?o))
                 (at end (not (clear ?o)))
                 (at end (not (object-at ?o ?l)))
                 (at end (decrease (battery-level ?r) 0.05)))
  )
  (:durative-action pour
    :parameters (?r - robot ?src ?tgt - object ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (holding ?r ?src))
                    (at start (at ?r ?l))
                    (at start (object-at ?tgt ?l))
                    (over all (battery-ok ?r))
                    (over all (>= (battery-level ?r) 0.1)))
    :effect (and (at end (poured ?src ?tgt))
                 (at end (decrease (battery-level ?r) 0.1)))
  )
  (:durative-action validate-motion
    :parameters (?from ?to - location)
    :duration (= ?duration 1)
    :condition (and (at start (reachable ?from ?to)))
    :effect (at end (motion-validated ?from ?to))
  )
  (:durative-action recharge
    :parameters (?r - robot ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?r ?l)))
    :effect (and (at end (assign (battery-level ?r) 1.0))
                 (at end (battery-ok ?r)))
  )
)
