(define (domain hybrid_domain)
  (:requirements :durative-actions :typing :fluents :numeric-fluents)
  (:types robot location object)
  (:predicates
    (at ?r - robot ?l - location)
    (connected ?from ?to - location)
    (holding ?r - robot ?o - object)
    (clear ?o - object)
    (poured ?o - object ?t - object)
    (reachable ?from ?to - location)
    (battery-ok ?r - robot)
  )
  (:functions
    (distance ?from ?to - location)
    (battery-level ?r - robot)
    (travel-time ?from ?to - location)
  )
  (:process battery-drain
    :parameters (?r - robot)
    :precondition (moving ?r)
    :effect (decrease (battery-level ?r) (* #t 0.05))
  )
  (:durative-action move
    :parameters (?r - robot ?from ?to - location)
    :duration (= ?duration (travel-time ?from ?to))
    :condition (and (at start (at ?r ?from))
                    (at start (reachable ?from ?to))
                    (over all (battery-ok ?r)))
    :effect (and (at start (not (at ?r ?from)))
                 (at end (at ?r ?to)))
  )
  (:durative-action pick
    :parameters (?r - robot ?o - object ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?r ?l))
                    (at start (clear ?o)))
    :effect (and (at end (holding ?r ?o))
                 (at end (not (clear ?o))))
  )
  (:durative-action pour
    :parameters (?r - robot ?src ?tgt - object)
    :duration (= ?duration 3)
    :condition (and (at start (holding ?r ?src))
                    (over all (battery-ok ?r)))
    :effect (at end (poured ?src ?tgt))
  )
)
